version: "3"

services:
  api:
    build: ./
    entrypoint: ["sh", "-c", "cd src/prisma && npx prisma generate && npx prisma migrate deploy && npm start"]
    container_name: bookshelf-api
    volumes:
      - ./:/app/
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: nodedrf
    container_name: bookshelf-db
    ports:
      - "5432:5432"